# Generated by Django 2.2.6 on 2019-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='media/media/users/tj.png', null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
