# Generated by Django 2.2.6 on 2019-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191027_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.IntegerField(choices=[('student', 'Студент'), ('teacher', 'Предодаватель')], default=None, verbose_name='кто Вы'),
        ),
    ]
