# Generated by Django 2.2.6 on 2019-10-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191027_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.IntegerField(choices=[('student', 'Студент'), ('teacher', 'Предодаватель')], default='', verbose_name='кто Вы'),
        ),
    ]
