# Generated by Django 2.2.6 on 2019-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191027_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='users/tj.png', null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
