# Generated by Django 2.2.6 on 2019-10-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191027_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Предодаватель')], max_length=128, verbose_name='кто Вы'),
        ),
    ]
