# Generated by Django 2.2.6 on 2019-10-27 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savolho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовка')),
                ('savol', models.TextField(verbose_name='Вопрос')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Нашр шуд')),
                ('image', models.ImageField(blank=True, null=True, upload_to='from_questions/', verbose_name='рисунок')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Subject', verbose_name='Фан')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
